import type { Project } from './types.ts';

export const PROJECTS: Project[] = [
    {
        id: 601,
        title: "REFLECTIA",
        category: "CODE",
        categories: ["ux-product"],
        type: "AIRPLAY FOR WINDOWS",
        status: "DEV",
        desc: "Receptor AirPlay para Windows: recibe y controla en vivo la pantalla de dispositivos Apple, con capturas, controles remotos y un agente asistente.",
        lvl: 90,
        image: "https://image.qwenlm.ai/public_source/23d877b0-76cf-4d4b-9e00-e3a5689648a5/1db405957-218e-44cc-9c80-23b2b7af4fc4.png",
        viewerMode: "live",
        viewerProfile: "webapp",
        liveInterface: "reflectia",
        caseStudy: {
            context: "Diseño y desarrollo de la interface del receptor AirPlay para Windows (Reflectia): reproducir y operar un dispositivo Apple desde la PC.",
            contribution: "Interface completa de streaming: ventana simulada del sistema, panel de herramientas, pantalla de transmisión en vivo y agente conversacional que opera la sesión.",
            process: ["Ventana simulada (shell) con controles de sistema", "Panel de dispositivos AirPlay", "Pantalla de transmisión con capturas", "Agente asistente con acciones"],
            evidence: ["Interface interactiva integrada en el monitor", "Controles remotos funcionales", "Capturas y biblioteca en vivo"]
        }
    },
    {
        id: 501,
        title: "NODIA",
        category: "CODE",
        categories: ["systems-ai"],
        type: "AI ASSISTANT",
        status: "DEV",
        desc: "Asistente inteligente y entorno de ejecución interactivo con arquitectura de agentes.",
        lvl: 95,
        image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
        viewerMode: "live",
        viewerProfile: "webapp",
        launchApp: "browser",
        launchId: "nodia",
        embedUrl: "https://ai.studio/apps/5ac40848-da28-4343-bd7f-9a7c94f40188?fullscreenApplet=true",
        url: "https://ai.studio/apps/5ac40848-da28-4343-bd7f-9a7c94f40188?fullscreenApplet=true",
        featured: false
    },
    {
        id: 401,
        title: "VOYAGER OS",
        category: "CODE",
        categories: ["systems-ai"],
        type: "DESKTOP OS",
        status: "LIVE SYSTEM",
        desc: "Entorno de escritorio interactivo con dock inteligente, widgets extraíbles, reproductor de música, centro de notificaciones y búsqueda.",
        lvl: 99,
        image: "https://images.unsplash.com/photo-1687042277586-971369d3d241?q=80&w=600&auto=format&fit=crop",
        viewerMode: "live",
        viewerProfile: "webapp",
        launchApp: "browser",
        launchId: "voyager-os",
        caseStudy: {
            context: "Diseño y desarrollo de un entorno de escritorio web interactivo emulado dentro del monitor CRT 3:2.",
            contribution: "Arquitectura de componentes, microinteracciones del dock, widgets de escritorio y adaptabilidad fluida al CRT.",
            process: ["Integración de dock magnético", "Sistema de widgets y paneles", "Emulación en pantalla CRT", "Optimización de rendimiento"],
            evidence: ["Dock interactivo funcional", "Widgets extraíbles", "Integración completa sin cambiar el stack"],
            nextStep: "Añadir más applets nativos al ecosistema Voyager."
        }
    },
    {
        id: 301,
        title: "UNIBELANDS 3",
        category: "ARCHIVE",
        categories: ["archive"],
        type: "INTERACTIVE PORTFOLIO",
        status: "ARCHIVE",
        desc: "Portafolio horizontal en React, TypeScript y Three.js que organiza capacidades, proyectos y contacto como un mundo interactivo.",
        lvl: 0,
        image: "/assets/interface/puerta-portada.png",
        featured: false,
        viewerMode: "archive",
        viewerProfile: "archive",
        launchApp: "browser",
        launchId: "unibelands-3",
        caseStudy: {
            context: "Transformar un portafolio visual existente en una experiencia navegable que también permita una revisión profesional rápida.",
            contribution: "Arquitectura de experiencia, implementación frontend, estabilización responsive, accesibilidad y validación local del producto.",
            process: ["Inventario y puerta P0", "Estabilización de interacción", "Arquitectura de dos recorridos", "QA visual y técnico"],
            evidence: ["Build de producción", "Typecheck", "Matriz responsive", "Flujos de teclado y modales"],
            nextStep: "Publicar una versión revisada cuando los enlaces profesionales y el CV estén confirmados."
        }
    },
    { id: 201, title: "CAPTURE 01", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-01.png", url: "/assets/portfolio/imports/featured-portfolio-01.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 202, title: "CAPTURE 02", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-02.png", url: "/assets/portfolio/imports/featured-portfolio-02.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 203, title: "CAPTURE 03", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-03.png", url: "/assets/portfolio/imports/featured-portfolio-03.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 204, title: "CAPTURE 04", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-04.png", url: "/assets/portfolio/imports/featured-portfolio-04.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 205, title: "CAPTURE 05", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-05.png", url: "/assets/portfolio/imports/featured-portfolio-05.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 206, title: "CAPTURE 06", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-06.png", url: "/assets/portfolio/imports/featured-portfolio-06.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 207, title: "CAPTURE 07", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-07.png", url: "/assets/portfolio/imports/featured-portfolio-07.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 208, title: "CAPTURE 08", category: "ARCHIVE", categories: ["archive"], type: "MEDIA", status: "UNCLASSIFIED", desc: "Material visual importado pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-08.png", url: "/assets/portfolio/imports/featured-portfolio-08.png", mediaKind: "image", viewerProfile: "archive" },
    { id: 209, title: "IMPORTED RECORDING", category: "ARCHIVE", categories: ["archive"], type: "VIDEO", status: "UNCLASSIFIED", desc: "Grabación importada pendiente de contexto editorial y atribución.", lvl: 0, image: "/assets/portfolio/imports/featured-portfolio-01.png", url: "/assets/portfolio/imports/featured-recording.mp4", videoUrl: "/assets/portfolio/imports/featured-recording.mp4", mediaKind: "video", viewerProfile: "archive" },
    { id: 101, title: "CODEPEN JOXOMOD", category: "UI_UX", categories: ["ux-product"], type: "CODEPEN", status: "LIVE", desc: "Misión interactiva embebida desde CodePen para revisar comportamiento visual y microinteracciones.", lvl: 91, image: "/assets/portfolio/projects/039_nfzxv8g.png", url: "https://codepen.io/Daniel-Unibe/pen/JoXOmod", embedUrl: "https://codepen.io/Daniel-Unibe/embed/JoXOmod?default-tab=result&theme-id=dark&editable=false", viewerProfile: "codepen" },
    { id: 102, title: "CODEPEN RNAVQYJ", category: "UI_UX", categories: ["ux-product"], type: "CODEPEN", status: "LIVE", desc: "Prototipo vivo integrado como quest para validar layout, ritmo visual y respuesta de interfaz.", lvl: 89, image: "/assets/portfolio/projects/039_nfzxv8g.png", url: "https://codepen.io/Daniel-Unibe/pen/RNavqyJ", embedUrl: "https://codepen.io/Daniel-Unibe/embed/RNavqyJ?default-tab=result&theme-id=dark&editable=false", viewerProfile: "codepen" },
    { id: 103, title: "CODEPEN YPQGRPZ", category: "UI_UX", categories: ["ux-product"], type: "CODEPEN", status: "LIVE", desc: "Ejemplo UI/UX embebido en el registro de misiones para inspección directa dentro del HUD.", lvl: 87, image: "/assets/portfolio/projects/039_nfzxv8g.png", url: "https://codepen.io/Daniel-Unibe/pen/YPqgrpz", embedUrl: "https://codepen.io/Daniel-Unibe/embed/YPqgrpz?default-tab=result&theme-id=dark&editable=false", viewerProfile: "codepen" },
    { id: 104, title: "CODEPEN KWZYBXO", category: "UI_UX", categories: ["ux-product"], type: "CODEPEN", status: "LIVE", desc: "Módulo experimental de interfaz cargado como misión viva con enlace externo de respaldo.", lvl: 86, image: "/assets/portfolio/projects/039_nfzxv8g.png", url: "https://codepen.io/Daniel-Unibe/pen/Kwzybxo", embedUrl: "https://codepen.io/Daniel-Unibe/embed/Kwzybxo?default-tab=result&theme-id=dark&editable=false", viewerProfile: "codepen" },
    { id: 105, title: "CODEPEN YPQYZRX", category: "UI_UX", categories: ["ux-product"], type: "CODEPEN", status: "LIVE", desc: "Demo CodePen conectada al Quest Log como referencia viva para futuras iteraciones visuales.", lvl: 88, image: "/assets/portfolio/projects/039_nfzxv8g.png", url: "https://codepen.io/Daniel-Unibe/pen/YPqYZRX", embedUrl: "https://codepen.io/Daniel-Unibe/embed/YPqYZRX?default-tab=result&theme-id=dark&editable=false", viewerProfile: "codepen" },
    { id: 14, title: "KIRBY WORLD", category: "3D", categories: ["game-ui-3d"], type: "3D ART", status: "COMPLETE", desc: "Escenario completo inspirado en el universo de Kirby. Modelado procedural y texturizado estilizado.", lvl: 95, image: "/assets/portfolio/projects/020_daniel-unibe-kirbyword.jpg", url: "/offline-links/kirby-world.html", featured: false, viewerProfile: "media" },
    { id: 15, title: "DIORAMA STAGE", category: "3D", categories: ["game-ui-3d"], type: "ENV ART", status: "COMPLETE", desc: "Composición de diorama miniatura con iluminación dinámica y assets de alta fidelidad.", lvl: 88, image: "/assets/portfolio/projects/021_daniel-unibe-escenario.jpg", url: "/offline-links/diorama-stage.html", viewerProfile: "media" },
    { id: 16, title: "MICKEY PIECE", category: "3D", categories: ["game-ui-3d"], type: "3D ART", status: "COMPLETE", desc: "Escultura digital orgánica de pieza clásica. Enfoque en topología y renderizado de materiales.", lvl: 82, image: "/assets/portfolio/projects/022_daniel-unibe-mickey-pieza.jpg", url: "/offline-links/mickey-piece.html", viewerProfile: "media" },
    { id: 17, title: "HYDRANT PROP", category: "3D", categories: ["game-ui-3d"], type: "PROPS", status: "COMPLETE", desc: "Asset de entorno urbano (Hidrante). Flujo de trabajo High-to-Low poly optimizado para juegos.", lvl: 75, image: "/assets/portfolio/projects/023_daniel-unibe-hidrante-prueba-propp.jpg", url: "/offline-links/hydrant-prop.html", viewerProfile: "media" },
    { id: 18, title: "SCI-FI PISTOL", category: "3D", categories: ["game-ui-3d"], type: "PROPS", status: "COMPLETE", desc: "Diseño de arma futurista. Hard surface modeling con detalles mecánicos avanzados.", lvl: 90, image: "/assets/portfolio/projects/024_daniel-unibe-pistola-2.jpg", url: "/offline-links/scifi-pistol.html", featured: false, viewerProfile: "media" },
    { id: 19, title: "ROBOT RENDER", category: "3D", categories: ["game-ui-3d"], type: "CHAR", status: "COMPLETE", desc: "Concepto de personaje robótico. Integración de materiales metálicos y desgaste realista.", lvl: 85, image: "/assets/portfolio/projects/025_daniel-unibe-robotrenderdanielunibe.jpg", url: "/offline-links/robot-render.html", viewerProfile: "media" },
    { id: 20, title: "LUIGI BOO", category: "3D", categories: ["game-ui-3d"], type: "3D ART", status: "COMPLETE", desc: "Modelo estilizado basado en la mansión de Luigi. Renderizado con shaders personalizados.", lvl: 79, image: "/assets/portfolio/projects/026_daniel-unibe-luigiboo.jpg", url: "/offline-links/luigi-boo.html", viewerProfile: "media" },
    { id: 1, title: "PROYEC.TDH.IA", category: "CODE", categories: ["systems-ai"], type: "DEV", status: "ACTIVE", desc: "Sistema de inteligencia artificial integrado para la gestión de datos operativos complejos.", lvl: 99, image: "/assets/portfolio/projects/027_22xcxyj.png", viewerProfile: "webapp" },
    { id: 2, title: "PROYECTIA & OCTAVIA", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "LIVE", desc: "Ecosistema unificado de herramientas de IA para optimización de flujo creativo.", lvl: 92, image: "/assets/portfolio/projects/028_k9c6mz6.jpeg", viewerProfile: "webapp" },
    { id: 3, title: "PROYECTIA TABS", category: "UI_UX", categories: ["ux-product"], type: "PERSONAL", status: "BETA", desc: "Rediseño de navegación modular para interfaces de alta densidad de información.", lvl: 84, image: "/assets/portfolio/projects/029_jgdzjia.png", viewerProfile: "webapp" },
    { id: 4, title: "JULIA {IA}", category: "CODE", categories: ["systems-ai", "featured"], type: "DEV", status: "DEV", desc: "Producto de asistencia con interfaz web y escritorio en desarrollo.", lvl: 88, image: "/assets/portfolio/projects/030_yadesbg.png", featured: true, viewerProfile: "webapp" },
    { id: 5, title: "NEKIRA IA", category: "CODE", categories: ["systems-ai"], type: "DEV", status: "CONCEPT", desc: "Núcleo de IA generativa para la creación automática de estructuras lógicas de software.", lvl: 70, image: "/assets/portfolio/projects/031_cimjm1p.png", viewerProfile: "webapp" },
    { id: 6, title: "NEKO NESUSHI", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "CONCEPT", desc: "Proyecto arcade experimental centrado en mecánicas de ritmo y precisión visual.", lvl: 65, image: "/assets/portfolio/projects/032_98pebzb.png", viewerProfile: "media" },
    { id: 7, title: "NEKO NESUSHI LITE", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "MOBILE", desc: "Versión optimizada para dispositivos móviles con latencia de entrada ultra-baja.", lvl: 60, image: "/assets/portfolio/projects/033_qym8txl.png", viewerProfile: "media" },
    { id: 8, title: "KAETSO", category: "3D", categories: ["game-ui-3d"], type: "3D", status: "CONCEPT", desc: "Visualizador de arquitectura modular en 3D para la previsualización de entornos técnicos.", lvl: 75, image: "/assets/portfolio/projects/034_cuo44ob.png", viewerProfile: "media" },
    { id: 9, title: "HOT DOG HERO!", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "CONCEPT", desc: "Simulador táctico con estilo visual de alta saturación y físicas exageradas.", lvl: 50, image: "/assets/portfolio/projects/035_lepwooy.jpeg", viewerProfile: "media" },
    { id: 10, title: "DIE RABBITS DIE", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "ARCADE", desc: "Shooter frenético estilo horda con sistema de progresión de habilidades no lineal.", lvl: 55, image: "/assets/portfolio/projects/036_8burs2t.jpeg", viewerProfile: "media" },
    { id: 11, title: "NANNY NINJA", category: "CODE", categories: ["systems-ai"], type: "PERSONAL", status: "GAME JAM", desc: "Proyecto ganador de Game Jam: Acción stealth en entornos domésticos hiper-reactivos.", lvl: 62, image: "/assets/portfolio/projects/037_dihgfh6.jpeg", viewerProfile: "media" },
    { id: 12, title: "DRAGÓN ALEBRIJE", category: "UI_UX", categories: ["ux-product"], type: "UI/UX", status: "GDD", desc: "Documentación y diseño de interfaz para una aventura mitológica rica en color y forma.", lvl: 40, image: "/assets/portfolio/projects/038_jbvi7ml.png", viewerProfile: "media" },
    { id: 13, title: "THE GOOD LIAR", category: "UI_UX", categories: ["ux-product"], type: "UI/UX", status: "CONCEPT", desc: "Concepto de interfaz de usuario para juego de deducción social con estética Noir.", lvl: 48, image: "/assets/portfolio/projects/039_nfzxv8g.png", viewerProfile: "media" },
];

export const CATEGORY_ORDER = ['DESTACADOS', 'TODOS', 'UX_PRODUCT', 'GAME_UI_3D', 'SYSTEMS_AI', 'ARCHIVE'] as const;
